"""add savings_pockets and savings_pocket_movements tables

Revision ID: 31bd6b3c156a
Revises: 33b9649a6488
Create Date: 2026-06-03 03:56:25.897112

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '31bd6b3c156a'
down_revision: str | Sequence[str] | None = '33b9649a6488'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_pockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='Parent debit account that holds this pocket.'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Pocket name as reported by the bank, e.g. 'Ahorro', 'Renta', 'Cajita Gastos'."),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False when the pocket has been closed by the user.'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_savings_pocket_account_name'),
    comment="Named savings sub-accounts within a debit account. MercadoPago calls these 'Apartados'; Nu calls them 'Cajitas'."
    )
    with op.batch_alter_table('savings_pockets', schema=None) as batch_op:
        batch_op.create_index('ix_savings_pocket_account', ['account_id'], unique=False)

    op.create_table('savings_pocket_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pocket_id', sa.Integer(), nullable=False, comment='Pocket this movement belongs to.'),
    sa.Column('transaction_id', sa.Integer(), nullable=False, comment='Source transaction record for this movement.'),
    sa.Column('movement_type', sa.String(length=20), nullable=False, comment='deposit | withdrawal | interest'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Absolute movement amount (always positive).'),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=True, comment='Pocket balance after this movement. NULL if not reported by the bank.'),
    sa.CheckConstraint("movement_type IN ('deposit', 'withdrawal', 'interest')", name='ck_pocket_movement_type'),
    sa.ForeignKeyConstraint(['pocket_id'], ['savings_pockets.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Each deposit into, withdrawal from, or interest credited to a savings pocket. Linked to the originating transaction row.'
    )
    with op.batch_alter_table('savings_pocket_movements', schema=None) as batch_op:
        batch_op.create_index('ix_pocket_movement_pocket', ['pocket_id'], unique=False)
        batch_op.create_index('ix_pocket_movement_transaction', ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_pocket_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_pocket_movement_transaction')
        batch_op.drop_index('ix_pocket_movement_pocket')

    op.drop_table('savings_pocket_movements')
    with op.batch_alter_table('savings_pockets', schema=None) as batch_op:
        batch_op.drop_index('ix_savings_pocket_account')

    op.drop_table('savings_pockets')
    # ### end Alembic commands ###
