"""drop fee_transaction_id from cash_withdrawals

Revision ID: 33b9649a6488
Revises: af47d5171e32
Create Date: 2026-06-03 03:28:34.923603

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '33b9649a6488'
down_revision: str | Sequence[str] | None = 'af47d5171e32'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('cash_withdrawals', schema=None) as batch_op:
        batch_op.drop_column('fee_transaction_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_transaction_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'transactions', ['fee_transaction_id'], ['id'])

    # ### end Alembic commands ###
