"""generalize cash_withdrawals: withdrawal_type and withdrawal_point

Revision ID: af47d5171e32
Revises: c1b8a1086331
Create Date: 2026-06-03 02:56:40.177886

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'af47d5171e32'
down_revision: str | Sequence[str] | None = 'c1b8a1086331'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withdrawal_type', sa.String(length=20), nullable=False, comment='Point type: atm | convenience_store | bank_branch | other.'))
        batch_op.add_column(sa.Column('withdrawal_point', sa.String(length=200), nullable=True, comment="Name of the withdrawal point as reported by the bank, e.g. 'OXXO ZARCO MEX'."))
        batch_op.drop_column('atm_name')

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_transfer_spei_tracking_key', ['spei_tracking_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_transfer_spei_tracking_key', type_='unique')

    with op.batch_alter_table('cash_withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atm_name', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('withdrawal_point')
        batch_op.drop_column('withdrawal_type')

    # ### end Alembic commands ###
