"""initial schema

Revision ID: c1b8a1086331
Revises:
Create Date: 2026-06-01 01:03:52.901657

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1b8a1086331"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "bank",
            sa.String(length=20),
            nullable=False,
            comment="Bank identifier. Valid values: nu, bbva, banamex, mercadopago",
        ),
        sa.Column(
            "account_type",
            sa.String(length=10),
            nullable=False,
            comment="Account type. Valid values: credit, debit",
        ),
        sa.Column(
            "clabe",
            sa.String(length=18),
            nullable=True,
            comment="18-digit CLABE — natural unique key. NULL for cards without CLABE.",
        ),
        sa.Column(
            "account_number",
            sa.String(length=30),
            nullable=True,
            comment="Internal account number assigned by the bank.",
        ),
        sa.Column(
            "last4",
            sa.String(length=4),
            nullable=True,
            comment="Last 4 digits of the card. Only populated for credit accounts.",
        ),
        sa.Column(
            "alias",
            sa.String(length=100),
            nullable=False,
            comment="Human-readable label, e.g. 'Nu Debit CDMX'.",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 currency code. Defaults to MXN.",
        ),
        sa.Column(
            "credit_limit",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
            comment="Credit limit in MXN. NULL for debit accounts.",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Set to False to archive the account without deleting its data.",
        ),
        sa.CheckConstraint("account_type IN ('credit', 'debit')", name="ck_account_type"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clabe"),
        comment="Catalog of all bank accounts. CLABE is the natural unique identifier.",
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Category name, e.g. 'Food', 'Transport'.",
        ),
        sa.Column(
            "color",
            sa.String(length=7),
            nullable=True,
            comment="Hex color code for UI display, e.g. '#FF5733'.",
        ),
        sa.Column(
            "icon", sa.String(length=50), nullable=True, comment="Icon identifier for UI display."
        ),
        sa.Column(
            "parent_id",
            sa.Integer(),
            nullable=True,
            comment="Parent category ID. NULL means this is a top-level category.",
        ),
        sa.Column(
            "budget_mxn",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
            comment="Monthly budget in MXN. Used for alerts in the dashboard.",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Hierarchical spending categories. parent_id enables sub-categories.",
    )
    op.create_table(
        "installment_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "account_id",
            sa.Integer(),
            nullable=False,
            comment="Credit account where the MSI plan was opened.",
        ),
        sa.Column(
            "merchant",
            sa.String(length=200),
            nullable=False,
            comment="Merchant name as extracted from the PDF.",
        ),
        sa.Column(
            "original_amount",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Total purchase amount before splitting into installments.",
        ),
        sa.Column(
            "total_installments",
            sa.Integer(),
            nullable=False,
            comment="Total number of monthly installments, e.g. 6, 12, 18.",
        ),
        sa.Column(
            "interest_rate",
            sa.Numeric(precision=5, scale=4),
            nullable=False,
            comment="Monthly interest rate. 0.0000 for MSI (sin interés) plans.",
        ),
        sa.Column(
            "start_date", sa.Date(), nullable=False, comment="Date of the original purchase."
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Plan status. Valid values: active, completed, cancelled.",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'completed', 'cancelled')", name="ck_installment_plan_status"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="MSI (meses sin interés) purchase plans from Nu and Banamex. status valid values: active, completed, cancelled.",
    )
    with op.batch_alter_table("installment_plans", schema=None) as batch_op:
        batch_op.create_index(
            "ix_installment_plan_account_status", ["account_id", "status"], unique=False
        )

    op.create_table(
        "labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "pattern_regex",
            sa.String(length=200),
            nullable=False,
            comment="Python regex pattern matched against transaction description.",
        ),
        sa.Column(
            "category_id",
            sa.Integer(),
            nullable=False,
            comment="Category assigned when the pattern matches.",
        ),
        sa.Column(
            "priority",
            sa.Integer(),
            nullable=False,
            comment="Evaluation order. Lower number = higher priority.",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Regex-based auto-categorization rules. Evaluated in ascending priority order.",
    )
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.create_index("ix_label_priority", ["priority"], unique=False)

    op.create_table(
        "statements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "account_id", sa.Integer(), nullable=False, comment="Account this statement belongs to."
        ),
        sa.Column(
            "period_start", sa.Date(), nullable=False, comment="Start of the billing period."
        ),
        sa.Column(
            "period_end",
            sa.Date(),
            nullable=False,
            comment="End of the billing period / cutoff date.",
        ),
        sa.Column(
            "payment_due_date",
            sa.Date(),
            nullable=True,
            comment="Payment due date. Only populated for credit accounts.",
        ),
        sa.Column(
            "opening_balance",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
            comment="Balance at the start of the period.",
        ),
        sa.Column(
            "closing_balance",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
            comment="Balance at the end of the period / amount to avoid interest charges.",
        ),
        sa.Column(
            "minimum_payment",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
            comment="Minimum payment required. Only populated for credit accounts.",
        ),
        sa.Column(
            "file_path",
            sa.String(length=500),
            nullable=False,
            comment="Absolute path to the original PDF on disk.",
        ),
        sa.Column(
            "imported_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when this statement was imported.",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "period_start", "period_end", name="uq_statement_period"),
        comment="One record per imported PDF. Prevents importing the same period twice.",
    )
    with op.batch_alter_table("statements", schema=None) as batch_op:
        batch_op.create_index(
            "ix_statement_account_period",
            ["account_id", "period_start", "period_end"],
            unique=False,
        )

    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "account_id",
            sa.Integer(),
            nullable=False,
            comment="Account that originated this movement.",
        ),
        sa.Column(
            "statement_id",
            sa.Integer(),
            nullable=False,
            comment="Statement where this transaction appeared.",
        ),
        sa.Column(
            "category_id",
            sa.Integer(),
            nullable=True,
            comment="Assigned category. NULL until categorized.",
        ),
        sa.Column(
            "installment_plan_id",
            sa.Integer(),
            nullable=True,
            comment="Reference to the MSI plan if this transaction is an installment payment.",
        ),
        sa.Column(
            "date", sa.Date(), nullable=False, comment="Transaction date as reported by the bank."
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=False,
            comment="Raw description exactly as it appears in the PDF.",
        ),
        sa.Column(
            "merchant",
            sa.String(length=200),
            nullable=True,
            comment="Normalized merchant name after post-processing.",
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Amount in the original transaction currency.",
        ),
        sa.Column(
            "amount_mxn",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Amount converted to MXN for cross-account aggregations.",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 currency code of the original transaction.",
        ),
        sa.Column(
            "transaction_type",
            sa.String(length=20),
            nullable=False,
            comment="Movement type. Valid values: charge, payment, refund, interest.",
        ),
        sa.Column(
            "bank_reference",
            sa.String(length=100),
            nullable=True,
            comment="Bank's own unique identifier for this movement.",
        ),
        sa.Column(
            "is_internal_transfer",
            sa.Boolean(),
            nullable=False,
            comment="True when the counterpart CLABE matches a known account. Detected by comparing to_clabe against accounts.clabe — never by name.",
        ),
        sa.CheckConstraint(
            "transaction_type IN ('charge', 'payment', 'refund', 'interest')",
            name="ck_transaction_type",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["installment_plan_id"],
            ["installment_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["statements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Core table — all movements from all banks unified in a single schema. transaction_type valid values: charge, payment, refund, interest.",
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index("ix_transaction_account_date", ["account_id", "date"], unique=False)
        batch_op.create_index("ix_transaction_category", ["category_id"], unique=False)
        batch_op.create_index("ix_transaction_date", ["date"], unique=False)
        batch_op.create_index("ix_transaction_statement", ["statement_id"], unique=False)
        batch_op.create_index("ix_transaction_type", ["transaction_type"], unique=False)

    op.create_table(
        "cash_withdrawals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "account_id",
            sa.Integer(),
            nullable=False,
            comment="Debit account from which cash was withdrawn.",
        ),
        sa.Column(
            "transaction_id",
            sa.Integer(),
            nullable=False,
            comment="Transaction record for the withdrawal amount.",
        ),
        sa.Column(
            "category_id",
            sa.Integer(),
            nullable=True,
            comment="Category assigned to this withdrawal, e.g. 'Cash expenses'.",
        ),
        sa.Column(
            "fee_transaction_id",
            sa.Integer(),
            nullable=True,
            comment="Separate transaction record for the ATM fee charge. NULL if no fee was applied.",
        ),
        sa.Column(
            "atm_name",
            sa.String(length=200),
            nullable=True,
            comment="ATM name as reported by the bank, e.g. 'OXXO ZARCO MEX'.",
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Amount withdrawn in the original currency.",
        ),
        sa.Column(
            "currency", sa.String(length=3), nullable=False, comment="ISO 4217 currency code."
        ),
        sa.Column(
            "amount_mxn",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Amount converted to MXN.",
        ),
        sa.Column(
            "fee_amount",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="ATM fee charged. 0.00 if withdrawal was at the account's own bank ATM.",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fee_transaction_id"],
            ["transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="ATM cash withdrawals. Modeled separately from transfers because money leaves the trackable banking system — there is no destination account.",
    )
    with op.batch_alter_table("cash_withdrawals", schema=None) as batch_op:
        batch_op.create_index("ix_cash_withdrawal_account", ["account_id"], unique=False)

    op.create_table(
        "installments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "plan_id", sa.Integer(), nullable=False, comment="MSI plan this installment belongs to."
        ),
        sa.Column(
            "transaction_id",
            sa.Integer(),
            nullable=True,
            comment="Transaction where this installment charge appeared. NULL for future installments.",
        ),
        sa.Column(
            "installment_number",
            sa.Integer(),
            nullable=False,
            comment="Sequential number, e.g. 1 of 12.",
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Amount charged in this installment.",
        ),
        sa.Column(
            "due_date",
            sa.Date(),
            nullable=True,
            comment="Expected charge date for this installment.",
        ),
        sa.Column(
            "is_paid",
            sa.Boolean(),
            nullable=False,
            comment="True when the installment has appeared in a statement.",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["installment_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Individual monthly payment within an MSI plan. One record per billing cycle.",
    )
    with op.batch_alter_table("installments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_installment_plan_number", ["plan_id", "installment_number"], unique=False
        )

    op.create_table(
        "transfers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "transaction_id",
            sa.Integer(),
            nullable=False,
            comment="Source transaction this transfer is linked to.",
        ),
        sa.Column(
            "spei_tracking_key",
            sa.String(length=30),
            nullable=True,
            comment="BANXICO global unique tracking key (up to 30 chars). Format varies by bank: BBVA starts with 'MBAN', Nu with 'NU39', Mercado Pago with 'CPO'.",
        ),
        sa.Column(
            "spei_reference",
            sa.String(length=10),
            nullable=True,
            comment="Short numeric reference chosen by the sender (up to 10 digits in practice).",
        ),
        sa.Column(
            "counterpart_bank_code",
            sa.String(length=3),
            nullable=True,
            comment="First 3 digits of the counterpart's CLABE. E.g. 722=MercadoPago, 638=Nu, 012=BBVA.",
        ),
        sa.Column(
            "from_account_id",
            sa.Integer(),
            nullable=True,
            comment="Sending account if it belongs to the user. NULL if external.",
        ),
        sa.Column(
            "from_external_name",
            sa.String(length=200),
            nullable=True,
            comment="Name of the external sender as reported by BANXICO.",
        ),
        sa.Column(
            "to_account_id",
            sa.Integer(),
            nullable=True,
            comment="Receiving account if it belongs to the user. NULL if external.",
        ),
        sa.Column(
            "to_external_name",
            sa.String(length=200),
            nullable=True,
            comment="Name of the external beneficiary as reported by BANXICO.",
        ),
        sa.Column(
            "to_clabe",
            sa.String(length=18),
            nullable=True,
            comment="Destination CLABE — always 18 clean digits. For BBVA, the parser strips the '00' prefix from the 20-digit raw number.",
        ),
        sa.Column(
            "transfer_type",
            sa.String(length=10),
            nullable=False,
            comment="Transfer direction. Valid values: internal, outgoing, incoming.",
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Amount in the original transaction currency.",
        ),
        sa.Column(
            "currency", sa.String(length=3), nullable=False, comment="ISO 4217 currency code."
        ),
        sa.Column(
            "amount_mxn",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Amount converted to MXN.",
        ),
        sa.Column("date", sa.Date(), nullable=False, comment="Transfer date."),
        sa.CheckConstraint(
            "transfer_type IN ('internal', 'outgoing', 'incoming')", name="ck_transfer_type"
        ),
        sa.ForeignKeyConstraint(
            ["from_account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spei_tracking_key"),
        sa.UniqueConstraint("spei_tracking_key", name="uq_transfer_spei_tracking_key"),
        comment="SPEI bank transfers with identifiable counterpart. Internal detection is done by comparing to_clabe against accounts.clabe — never by name. transfer_type valid values: internal, outgoing, incoming.",
    )
    with op.batch_alter_table("transfers", schema=None) as batch_op:
        batch_op.create_index("ix_transfer_to_clabe", ["to_clabe"], unique=False)
        batch_op.create_index("ix_transfer_transaction", ["transaction_id"], unique=False)
        batch_op.create_index("ix_transfer_type", ["transfer_type"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transfers", schema=None) as batch_op:
        batch_op.drop_index("ix_transfer_type")
        batch_op.drop_index("ix_transfer_transaction")
        batch_op.drop_index("ix_transfer_to_clabe")

    op.drop_table("transfers")
    with op.batch_alter_table("installments", schema=None) as batch_op:
        batch_op.drop_index("ix_installment_plan_number")

    op.drop_table("installments")
    with op.batch_alter_table("cash_withdrawals", schema=None) as batch_op:
        batch_op.drop_index("ix_cash_withdrawal_account")

    op.drop_table("cash_withdrawals")
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_transaction_type")
        batch_op.drop_index("ix_transaction_statement")
        batch_op.drop_index("ix_transaction_date")
        batch_op.drop_index("ix_transaction_category")
        batch_op.drop_index("ix_transaction_account_date")

    op.drop_table("transactions")
    with op.batch_alter_table("statements", schema=None) as batch_op:
        batch_op.drop_index("ix_statement_account_period")

    op.drop_table("statements")
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.drop_index("ix_label_priority")

    op.drop_table("labels")
    with op.batch_alter_table("installment_plans", schema=None) as batch_op:
        batch_op.drop_index("ix_installment_plan_account_status")

    op.drop_table("installment_plans")
    op.drop_table("categories")
    op.drop_table("accounts")
    # ### end Alembic commands ###
